### ISSUE TITLE
Inline fold not working in .blade.php files

### ISSUE THREAD

**Issue by MightyCryptowall** [moalamri/vscode-inline-fold#50]
<img width="1322" alt="Screen Shot 2022-08-28 at 18 37 13" src="https://user-images.githubusercontent.com/52656718/187073390-7f7fe2d3-77e0-4ad6-86b4-4e5422e9adab.png">

**Comment by moalamri** [comment]
Add `php` in the extension's settings under `inlineFold.supportedLanguages`

```jsonc
{
"inlineFold.supportedLanguages": [
"php"
]
}
```

**Comment by MightyCryptowall** [comment]
@moalamri ,
updated the settings.json
<img width="548" alt="Screen Shot 2022-08-29 at 13 41 46" src="https://user-images.githubusercontent.com/52656718/187144227-91869dfa-fb37-4761-801a-664e255781e3.png">
n

but inline fold still not working after that

**Comment by moalamri** [comment]
fixed in #51

**Comment by MightyCryptowall** [comment]
> fixed in #51

@moalamri, inline fold still not working in .php and .blade.php files.

**Comment by e-medeiros** [comment]
@MightyCryptowall since new was not released add "php" and "blade" to the Supported languages in the "inline fold settings"

**Comment by MightyCryptowall** [comment]
@e-medeiros 
I already added, it still not working

I also restart the vscode.
I also uninstall and reinstall the extension

still not working in php files


vscode settings.
<img width="423" alt="Screen Shot 2022-09-04 at 17 59 54" src="https://user-images.githubusercontent.com/52656718/188311032-903df422-4b6d-4ad8-b0f6-10d709951cff.png">

settings.json
<img width="507" alt="Screen Shot 2022-09-04 at 18 01 13" src="https://user-images.githubusercontent.com/52656718/188311091-8c823105-1e02-4a7b-a15d-8bbad24375d1.png">

**Comment by moalamri** [comment]
@MightyCryptowall Sorry I'm really caught up by work.
I thought of releasing it with some changes I made. since you had it working then yes probably gonna release it with some changes that address another suggestion.
